### ISSUE TITLE
Change license to AGPLv3 or later

### ISSUE THREAD

**Issue by pizzamaker** [tchoulihan/referendum#1]
"AGPLv3 or later" closes an important loophole in GPLv3, regarding web apps: https://en.wikipedia.org/wiki/Affero_General_Public_License

This is a friendly suggestion so as to not have this code proprietarized by someone else :)

**Comment by tchoulihan** [comment]
I would have to learn more about this before I use it, I haven't heard of anyone having issues with the GPLv3. 

At least from the wiki : 

> where, by using but not distributing the software, the copyleft provisions are not triggered.

I have a release out, which should count as distributing the code.
