### ISSUE TITLE
Tags Are Created for Unpublished Polls

### ISSUE THREAD

**Issue by etsr** [tchoulihan/referendum#5]
After creating a tag in the form, regardless of whether the poll is published the tag is created. This would mean that if a poll containing sensitive information pertaining toward an organizing campaign or otherwise might accidentally be included without even being associated with a poll. This also will result in tags that may have errors being published, and likely re-published with a corrected spelling creating a flood of tags. Perhaps a system similar to what Stack Exchange has would be better suited to this site?

**Comment by tchoulihan** [comment]
> This would mean that if a poll containing sensitive information pertaining toward an organizing campaign or otherwise might accidentally be included without even being associated with a poll.

I don't know what an unpublished poll is. I think the trending pages will only render them if they have a subject, so are you talking about polls without subjects?

> This also will result in tags that may have errors being published

While you can't delete tags, you can delete the tags your poll has by clicking the `clear tags` button.

> Perhaps a system similar to what Stack Exchange has would be better suited to this site?

Stackexchange uses heavy moderation, based on points. Referendum is bottom-up democracy, not authoritative meritocracy, so it doesn't give special powers to anyone, and tags are completely unmoderated.

I don't see a reason that tags would need to be cleaned up, unless they were too long or short. Let anyone create and use any tag's they'd like, just like hashtags.

**Comment by etsr** [comment]
That makes more sense, I was thinking that perhaps if someone left sensitive information like a workplace they planned on organizing in the tags without publishing that it would likely be displayed at the bottom of the page, but the system functioning like the Twitter tag system makes a lot of sense.

**Comment by tchoulihan** [comment]
Ah I understand you now. Yep, just simple twitter-like tags, and letting anybody tag their polls however they'd like.
