### ISSUE TITLE
Allow Theme Changes

### ISSUE THREAD

**Issue by etsr** [tchoulihan/referendum#7]
Right now, and I think this was mentioned on reddit as well, the dark color scheme makes the page feel rather unfriendly. I'd be really interested in seeing options similar to the Github set of grays and whites as opposed to the black. I think the same can be said for the color scheme of the votes. The bright neon-like colors contrast well with the black, but really don't make the site feel welcoming or comfortable. It's not something I'd personally enjoy looking at for a long period of time.

**Comment by tchoulihan** [comment]
I'll think about this one. I do agree that a white theme would be more welcoming, but I'd like to preserve the possibility of using a dark theme for logged-in users.

**Comment by etsr** [comment]
Thanks. I know that in the comments on reddit one user referred to it as looking like a virtual parliament of the third Reich. I wouldn't go that far, but it is a little offensive on the eyes. I do think it's good to have choice, especially if that user is willing to open an account.
